version: "3"
services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"

  app:
    build: .
    links:
      - redis
    ports:
      - "80:8080"
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
